conf_threshold: 0.5
input_width: 960
input_height: 544
dataset_config:
  infer_data_sources:
    image_dir: TAO_DATA_PATH/raw-data/val2017/
    json_file: TAO_DATA_PATH/raw-data/annotations/instances_val2017.json
  num_classes: 91
  batch_size: 8
  workers: 8
color_map:
  person: green
  car: red
  cat: blue
model_config:
  num_feature_levels: 2
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  with_box_refine: True