num_gpus: 1
num_nodes: 1
val_interval: 1
dataset_config:
  train_data_sources:
    - image_dir: /data/coco2017/images/train2017/
      json_file: /data/coco2017/annotations/instances_train2017.json
  val_data_sources:
    - image_dir: /data/coco2017/images/val2017/
      json_file: /data/coco2017/annotations/instances_val2017.json
  num_classes: 91
  batch_size: 2
  workers: 8
model_config:
  backbone: resnet50
  num_feature_levels: 2
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  with_box_refine: True
  dropout_ratio: 0.3
train_config:
  optim:
    lr_backbone: 2e-5
    lr: 2e-4
    lr_steps: [10, 20, 30, 40]
    momentum: 0.9
  epochs: 50