sets: [afw]
gt_path: 'data'
save_path: 'data/tfrecords'
gt_root_path: '/workspace/tao-experiments/fpenet'
save_root_path: '/workspace/tao-experiments/fpenet'
image_root_path: '/workspace/tao-experiments/fpenet'
tfrecord_folder: 'FpeTfRecords'
tfrecord_name: 'data.tfrecords'
num_keypoints: 80
bbox_enlarge_ratio: 1.0