results_dir: /results/of_3d_ptm
encryption_key: nvidia_tao
model:
  model_type: of
  backbone: resnet_18
  rgb_seq_length: 3
  input_height: 224
  input_width: 224
  input_type: 3d
  sample_strategy: consecutive
  dropout_ratio: 0.0
dataset:
  train_dataset_dir: TAO_DATA_PATH/train
  val_dataset_dir: TAO_DATA_PATH/test
  label_map:
    fall_floor: 0
    ride_bike: 1
  batch_size: 32
  workers: 8
  clips_per_video: 5
  augmentation_config:
    train_crop_type: no_crop
    horizontal_flip_prob: 0.5
    rgb_input_mean: [0.5]
    rgb_input_std: [0.5]
    val_center_crop: False
evaluate:
  checkpoint: "??"
  test_dataset_dir: "??"