output_dir: /results/joint_2d
encryption_key: nvidia_tao
model_config:
  model_type: joint
  backbone: resnet18
  rgb_seq_length: 3
  rgb_pretrained_model_path: /results/rgb_2d/rgb_only_model.tlt
  of_seq_length: 16 
  of_pretrained_model_path: /results/of_2d/of_only_model.tlt
  input_type: 2d
  sample_strategy: consecutive
  dropout_ratio: 0.0
train_config:
  optim:
    lr: 0.0005
    momentum: 0.9
    weight_decay: 0.0
    lr_scheduler: MultiStep
    lr_steps: [5, 15]
    lr_decay: 0.1
  epochs: 20
  checkpoint_interval: 1
dataset_config:
  train_dataset_dir: /data/train
  val_dataset_dir: /data/test
  label_map:
    walk: 0
    sits: 1
    squa: 2
    fall: 3
    bend: 4
  output_shape:
  - 224
  - 224
  batch_size: 32
  workers: 8
  clips_per_video: 15
  augmentation_config:
    train_crop_type: no_crop
    #scales: [1.0, 0.875]
    horizontal_flip_prob: 0.0
    rgb_input_mean: [0.5]
    rgb_input_std: [0.5]
    of_input_mean: [0.5]
    of_input_std: [0.5]
    val_center_crop: False
