output_dir: "/results/nvidia"
encryption_key: nvidia_tao
model_config:
  model_type: ST-GCN
  in_channels: 3
  num_class: 6
  dropout: 0.5
  graph_layout: "nvidia"
  graph_strategy: "spatial"
  edge_importance_weighting: True
train_config:
  optim:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
    lr_scheduler: "MultiStep"
    lr_steps:
    - 10
    - 60
    lr_decay: 0.1
  epochs: 10
  checkpoint_interval: 5
dataset_config:
  train_data_path: "TAO_DATA_PATH/nvidia/train_data.npy"
  train_label_path: "TAO_DATA_PATH/nvidia/train_label.pkl"
  val_data_path: "TAO_DATA_PATH/nvidia/val_data.npy"
  val_label_path: "TAO_DATA_PATH/nvidia/val_label.pkl"
  label_map:
    sitting_down: 0
    getting_up: 1
    sitting: 2
    standing: 3
    walking: 4
    jumping: 5
  batch_size: 16
  workers: 5
